### ISSUE TITLE
Proposal feedback

### ISSUE THREAD

**Issue by mladenoff** [eshoule/throwback#1]
Overall, this looks very good. A couple things:

## MVPs
* I would do Auth before Hosting on Heroku (so you have something to host/test)
  * Really make it your (unwritten) goal to finish Auth on day one and at least attempt to set up Heroku that evening if possible. This will put you in the best possible position for finishing all of your MVPs.
* I would also adjust upload/download to come before music player.
  * This way you'll have things to play
  * The player can take a little bit of time, if for some reason you are unable to finish that (won't happen) at least you'll have upload/download complete
* To each non-Hosting/README MVP add:
    + "Adequate styling"
    + "Smooth, bug-free navigation"
    + "Seeded with info to demonstrate this feature"

## Schema
* You should have `band_name` not be a `not null` field, for non-band users
* Throw a boolean on there for an `is_fan?`
* Your `tracks` table will need an `ord` column for ordering the tracklist
  * Alternatively, you may want a joins table that has three columns, `track_id`, `album_id`, and `ord`
  * If `likes`/`follows` is to be just a bonus MVP, then this may be the route to go, or you will have no joins tables in your project

## State shape
* Each of your albums should probably have an array of their respective `songId`s, it will make playback simpler

## Routes
* Overall routes look good.
* Tracks should be nested
  * `POST /api/album/:id/album`
* If you don't map 1-to-1 users:bands then you'll need to do
  * `POST /api/artist/:id/album`
  * If you keep the 1:1 then no change here

**Comment by eshoule** [comment]
Fixed all of these.
